AppBundle\Entity\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
            groups: [Default]
        title:
            expose: true
            type: string
            groups: [Default]
        price:
            expose: true
            groups: [Default]
